Improve list item UI for directory
gravis-os/gravis-os pull request #500
Opened 2023-10-02 09:09 UTC by shank1xt

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

ui for list item and card is not complete

* **What is the new behavior (if this is a feature change)?**

improves ui for list item and card

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

* **Other information**:

2023-10-02 15:21 UTC, clodal requested changes

2023-10-02 15:21 UTC, clodal commented on packages/apps/src/directory/ListingCard.tsx
> +        sx={{ height: '100%', mt: is_listing_brand_image_enabled ? -6 : 0 }}
Odd to have -6 here

2023-10-02 15:21 UTC, clodal commented on packages/apps/src/directory/DirectoryTemplate.tsx
> +        isListMode
Are we able to manage these scenarios in the switch case instead? Want to keep the view clean

2023-10-02 15:21 UTC, clodal commented
@shank1xt Able to share screenshots as to what we're achieving here? Thanks

2023-10-03 01:43 UTC, shank1xt commented
<img width="1440" alt="image" src="https://github.com/gravis-os/gravis-os/assets/133622685/c9139848-adf4-499d-81d3-0793ed763163">

<img width="1440" alt="image" src="https://github.com/gravis-os/gravis-os/assets/133622685/5848af24-2f53-4309-b446-f457b8200cb5">

2023-10-03 05:31 UTC, clodal approved these changes

2023-10-03 05:32 UTC, merged